using System.Text.Json.Serialization;

namespace SwgLaunchpad.Core.Models;

/// <summary>
/// The per-server list of files that differ from the stock client, hosted at
/// files.fileManifestUrl and regenerated by the operator on every patch.
/// </summary>
public sealed class FileManifest
{
    [JsonPropertyName("generated")] public DateTimeOffset Generated { get; set; }
    [JsonPropertyName("files")] public List<ManifestFile> Files { get; set; } = new();
}

public sealed class ManifestFile
{
    /// <summary>Relative path within the server's game folder. Forward slashes. No '..'.</summary>
    [JsonPropertyName("path")] public string Path { get; set; } = "";
    [JsonPropertyName("size")] public long Size { get; set; }
    [JsonPropertyName("sha256")] public string Sha256 { get; set; } = "";
}
